[package]
name = "bzip2"
version = "1.0.8"
nanvix-version = "0.12.397"

[builds]
[builds.matrix]
platforms = ["hyperlight", "microvm"]
modes = ["multi-process", "single-process", "standalone"]
memory = ["128mb", "256mb"]

[[builds.exclude]]
platform = "hyperlight"
mode = "single-process"

[[builds.exclude]]
platform = "hyperlight"
mode = "multi-process"
